# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='tags',
            field=models.ManyToManyField(to='inventario.Tag'),
        ),
    ]
