# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.IntegerField()),
                ('localizacao', models.CharField(max_length=100)),
                ('sublocalizacao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
