# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0005_auto_20170410_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(choices=[('Emprestado', 'EMPRESTADO'), ('Devolvido', 'DEVOLVIDO')], max_length=10)),
                ('data_saida', models.DateTimeField()),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('item', models.ManyToManyField(to='inventario.Inventario')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
